name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build Docker image
        run: |
          nix --extra-experimental-features "nix-command flakes" build .#packages.x86_64-linux.docker
          docker load < result
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Push Docker image
        run: |
          docker tag gamerack:latest ghcr.io/${{ github.repository_owner }}/gamerack:latest
          docker push ghcr.io/${{ github.repository_owner }}/gamerack:latest
